<a href="https://colab.research.google.com/github/Argentan/DMA_LAB2/blob/master/tutoriales/03_manejo_de_datos-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/Argentan/DMA_LAB2/blob/master/tutoriales/03_manejo_de_datos-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Repaso de Listas

In [1]:
b = [1,2,3]

Aplicando Operadores Matemáticos a Listas

In [ ]:
b + b

In [ ]:
b * 4

Solución? For Loops?

In [ ]:
for elemento in b:
    print(elemento)

In [ ]:
for elemento in b:
    print(elemento + elemento)

Y si lo quiero guardar en otra variable (por ejemplo 'c = b+b')?

Una forma es:
* Definir un array vacio
* recorrer todos los elementos en b
* sumarlos entre si y meterlos dentro de una lista ([elemento + elemento])
* sumar esta lista a 'c' (**c \+= algo** es lo mismo que **c = c + algo**)

In [ ]:
c = []
for elemento in b:
    c += [elemento + elemento]
c

In [ ]:
c = []
for elemento in b:
    c += [elemento * 4]
c

Alternativa??

# Librería Numpy

Es el paquete de arrays mas comunmente usado en Python. La diferencia entre un array y una lista nativa es que el array es continuo en memoria mientras que la lista esta encadenada, haciendo que el array sea mucho mas rapido de leer y, por tanto, la estructura de datos natural para el procesamiento de grandes cantidades de datos

In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1 + arr1

array([2, 4, 6, 8])

In [7]:
arr1 / arr1

array([1., 1., 1., 1.])

In [8]:
arr1 + 100

array([101, 102, 103, 104])

## Dimensiones

Los arrays de numpy pueden ser unidimensionales (1D), bidimensionales (2D) o cuantas dimensiones quieran.


In [9]:
data = np.round( np.random.rand(3,5) * 100 )

In [10]:
data

array([[24., 39., 63.,  9., 29.],
       [55., 84., 47., 20.,  7.],
       [33., 73.,  3., 95., 92.]])

In [11]:
data * 2

array([[ 48.,  78., 126.,  18.,  58.],
       [110., 168.,  94.,  40.,  14.],
       [ 66., 146.,   6., 190., 184.]])

Tamaño de 'data'

In [12]:
data.shape

(3, 5)

## Indexado

El indexado en los ndarray funciona igual que el indexado de listas

Los elementos de una ndarray se pueden acceder mediante su indice

* Todos los indices empiezan en 0
* Se usan numeros enteros
* El indice maximo equivale a la (cantidad de elementos - 1)
* Se accede al elemento con *indice*
* Si el indice es negativo, se cuenta desde el final
* Se puede hacer "slicing" con rangos de indices separados por dos puntos (:)
* Se pueden usar indices negativos que cuentan desde atrás pero empezando en -1

In [13]:
arr1[0]

1

In [14]:
arr1[3]

4

In [15]:
arr1[len(arr1)]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [16]:
arr1[len(arr1) - 1]

4

In [17]:
arr1[-1]

4

In [18]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [19]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2d[:1]

array([[1, 2, 3]])

In [21]:
arr2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d[1, :2]

array([4, 5])

In [23]:
arr2d[:, 1]

array([2, 5, 8])

## Funciones de agregación

Suelen expresarse como métodos del objeto array. En general, tienen como consecuencia disminuir las dimensiones del arreglo y son muy utilizados en matemáticas y física. <br>
La siguiente tabla muestra los más utilizados, puede encontrar la documentación [aquí](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#calculation).

| Operación | Descripción |
|:----------|:------------|
| `a.sum()`    | Retorna la suma del arreglo en el eje dado |
| `a.min()`    | Retorna el valor mínimo de un eje |
| `a.mean()`   | Retorna la media aritmética en un eje dado |
| `a.var()`    | Retorna la varianza en un eje dado|
| `a.std()`    | Retorna la desviación estándar en un eje dado |
| `a.prod()`   | Retorna el producto en un eje dado |
| `a.argmin()` | Retorna el índice donde ocurren los valores mínimos de cada eje |
| `a.ptp()`    | Valor pico a pico en un eje |
| `a.conj()`   | Retorna el conjugado complejo de todos los elementos |
| `a.round()`  | Retorna el valor redondeado de cada elemento |
| `a.trace()`  | Retorna la suma de las diagonales del arreglo |
| `a.argmax()` | Retorna el índice donde ocurren los valores máximos de cada eje |
| `a.cumsum()` | Retorna la suma acumulativa en un eje dado |
| `a.cumprod()`| Retorna el producto acumulativo en un eje dado |

In [24]:
arr1.mean()

2.5

In [25]:
arr1.std()

1.118033988749895

In [26]:
arr1.shape

(4,)

In [27]:
arr1.size

4

In [28]:
arr2 = np.ones((2, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr1.argmax()

3

In [30]:
arr2.shape

(2, 3)

In [ ]:
arr2.size

In [ ]:
len(arr2)

## Funciones universales

Son funciones optimizadas que operan sobre el array. Dificilmente vamos a necesitar hacer algo que no este ya implementado, la lista completa de funciones universales en este [enlace](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#math-operations)

### Funciones para crear ndarrays

Hay muchas formas de crear arreglos en Numpy, puede explorarlas todas en este [enlace](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html). Las más comunes son:

| Función | Descripción |
|:--------|:------------|
| `empty` | Arreglo vacio |
| `zeros` | Arreglo de ceros |
| `ones`  | Arreglo de unos |
| `full`  | Se especifica un valor para llenar todo el arreglo con él |
| `identity` | Unos en la diagonal y cero en el resto |
| `array` | Constructor genérico |
| `fromfunction` | Según una función dada que retorna un valor para cada punto de la coordenada |
| `loadtxt` | Carga los datos de un archivo |

In [34]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.full([2,5], fill_value=10)



1.   Crear un array de 100 números aleatorios con valores de -100 a +100. 







# Ejercicios

In [78]:
import numpy as np
a = np.random.randint(-100, 100, size=100)
a

array([ -45,  -48,   43,   17,   33,    2,   77,  -70,  -66,  -94,  -97,
         11,    2,   47,   -4,  -73,  -78,  -36,  -63,   76,   78,    1,
        -36,  -24,  -24,   67,  -37,   11,  -25,   88,   76,   -1,   74,
        -12,    0,   -4,   14,  -13,   -7,  -63,  -62,  -26,  -41,  -10,
         40,  -68,  -82,  -44,   71,    4,   32,    2,  -61,   42,  -25,
         61,   57,   16,   -9,  -90,   32,   37,  -99,  -73,  -78,   57,
        -23,   99,  -36,  -77, -100,  -86,   67,   50,  -56,   11,  -68,
        -12,   55,   44,   14,   85,   18,  -32,  -32,   84,   -8,  -11,
         25,   70,   29,  -22,   28,   -5,  -78,  -16,   14,   21,  -83,
        -38])


2.   Usando arrays de booleanos crear otros 3 arrays que contengan los positivos, los negativos y los mayores de 50 de ese array.

In [54]:
pos = a[a> 0] 
neg = a[a<0]
mayor50 = a[a>50]

array([64, 81, 90, 97, 77, 92, 98, 60, 98, 89, 74, 60, 92, 64, 92, 96, 63,
       70, 59, 80, 98, 76, 66, 55, 87, 60, 64, 57, 76, 81, 87, 77, 78, 57,
       68, 86])

3.   Crear un array bidimensional 5x5 con todos los valores cero. Usando el indexado de arrays, asigna 1 a todos los elementos de la última fila y 5 a todos los elementos de la primera columna. Finalmente, asigna el valor 100 a todos los elementos del subarray central 3x3 de la matriz de 5x5.

In [100]:
a = np.zeros([5,5])
a[-1] = 1

a[:,0] = 5
a

array([[5., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0.],
       [5., 1., 1., 1., 1.]])

4.   Crear una matriz de 10 x 3 con valores aleatorios entre cero y uno



In [70]:
import numpy as np
a = np.random.rand(10,3)



5.   Buscar el valor mínimo de la matriz

In [72]:
a.min()

0.001826190203936373

6.   Buscar la posición (indice) del valor mínimo de la matriz

In [74]:
a.argmin()

16